
hostname=*slidebox-ios-prod.cloudfunctions.net

https:\/\/.*slidebox-ios-prod\.cloudfunctions\.net\/api_v1$ url script-response-body https://raw.githubusercontent.com/ne1av/learning/refs/heads/main/scripts/sbox.js
